- name: Install Docker Engine on Raspberry Pi OS - Bookworm
  hosts: all
  become: true
  vars:
    current_user: "{{ lookup('env', 'USER') }}"
  tasks:
    - name: Perform an apt update
      ansible.builtin.apt:
        state: present
        update_cache: true

    - name: Ensure python3-debian is installed
      ansible.builtin.apt:
        name: python3-debian
        state: present

    - name: Install required packages
      ansible.builtin.apt:
        name:
          - ca-certificates
          - curl
          - gnupg2
          - apt-transport-https
          - software-properties-common
        state: present

    - name: Add Docker Repo with GPG Key
      ansible.builtin.deb822_repository:
        name: docker
        types: [deb]
        architectures: [arm64]
        uris: ["https://download.docker.com/linux/debian"]
        suites: [bookworm]
        components: [stable]
        signed_by: https://download.docker.com/linux/debian/gpg
        state: present
        enabled: true

    - name: Install Docker Packages
      ansible.builtin.apt:
        state: present
        update_cache: true
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io

    - name: Add current user to Docker group
      ansible.builtin.user:
        name: "{{ current_user }}"
        groups: docker

    - name: Start Docker service
      ansible.builtin.service:
        name: docker
        state: started
